[package]
name = "cc-video-marker"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
resvg = "0.15.0"
tiny-skia = "0.5"
usvg = "0.15.0"
rayon = "1.5"
